namespace: rylanlabs
name: unifi
version: 2.3.0
readme: README.md
authors:
  - Security Council
description: Canonical UniFi Mesh Infrastructure Collection
license:
  - MIT
tags:
  - unifi
  - networking
  - security
  - mesh
dependencies:
  ansible.utils: ">=2.0.0"
repository: https://github.com/RylanLabs/rylan-labs-common
documentation: https://github.com/RylanLabs/rylan-labs-common/docs
homepage: https://github.com/RylanLabs/rylan-labs-common
issues: https://github.com/RylanLabs/rylan-labs-common/issues
build_ignore:
  - .audit
  - .backups
  - .rylan
  - tests
  - Makefile
  - common.mk
  - canon-manifest.yaml
